MODES
{
	Default();
}
CS
{
	#include "system.fxc"
	struct TransitionRequest { float4 FineOrigin; float4 CoarseOrigin; uint FineStep; uint CoarseStep; uint Face; uint Generation; uint RequestIndex; uint ResidentSlot; uint TransitionSlot; uint Reserved0; };
	struct AllocationDescriptor { uint VertexOffset; uint VertexCapacity; uint IndexOffset; uint IndexCapacity; uint Generation; uint ResidentSlot; uint RequestIndex; uint Flags; float4 DrawOrigin; float4 DrawScale; };
	struct VoxelGpuVertex { float3 Position; float3 Normal; float3 Tangent; float2 TexCoord; };
	StructuredBuffer<TransitionRequest> Requests < Attribute( "Requests" ); >; StructuredBuffer<float> Samples < Attribute( "Samples" ); >; StructuredBuffer<uint> Lookup < Attribute( "Lookup" ); >; StructuredBuffer<AllocationDescriptor> Allocations < Attribute( "Allocations" ); >; RWStructuredBuffer<VoxelGpuVertex> OutputVertices < Attribute( "OutputVertices" ); >; RWStructuredBuffer<uint> OutputIndices < Attribute( "OutputIndices" ); >;
	int ChunkSize < Attribute( "ChunkSize" ); >; int SampleCount < Attribute( "SampleCount" ); >; int BatchSize < Attribute( "BatchSize" ); >; int GeometryOffset < Attribute( "GeometryOffset" ); >; int TriangleOffset < Attribute( "TriangleOffset" ); >; int VertexOffset < Attribute( "VertexOffset" ); >; float VoxelSize < Attribute( "VoxelSize" ); >; float SdfClampDistance < Attribute( "SdfClampDistance" ); >; float SimplexFrequency < Attribute( "SimplexFrequency" ); >; float SimplexAmplitude < Attribute( "SimplexAmplitude" ); >; float SimplexBaseHeight < Attribute( "SimplexBaseHeight" ); >; int SimplexSeed < Attribute( "SimplexSeed" ); >;
	static const uint CaseOrder[9]={0,1,2,5,8,7,6,3,4}; static const int3 SampleCoordinates[9]={int3(0,0,0),int3(1,0,0),int3(2,0,0),int3(0,1,0),int3(1,1,0),int3(2,1,0),int3(0,2,0),int3(1,2,0),int3(2,2,0)};
	int Hash(int x,int y,int seed){int value=seed+x*374761393+y*668265263;value=(value^(value>>13))*1274126177;return value^(value>>16);} float2 Gradient(int index){if(index==0)return float2(1,0);if(index==1)return float2(-1,0);if(index==2)return float2(0,1);if(index==3)return float2(0,-1);if(index==4)return float2(.70710677,.70710677);if(index==5)return float2(-.70710677,.70710677);if(index==6)return float2(.70710677,-.70710677);return float2(-.70710677,-.70710677);} float SimplexNoise(float2 point){const float skew=.3660254038,unskew=.2113248654;float skewed=(point.x+point.y)*skew;int cellX=(int)floor(point.x+skewed),cellY=(int)floor(point.y+skewed);float cellOffset=(cellX+cellY)*unskew;float2 offset=point-(float2(cellX,cellY)-cellOffset);int sx=offset.x>offset.y?1:0,sy=offset.x>offset.y?0:1;float2 second=offset-float2(sx,sy)+unskew,third=offset-1+2*unskew;float value=0;float radius=.5-dot(offset,offset);if(radius>0)value+=radius*radius*radius*radius*dot(Gradient(Hash(cellX,cellY,SimplexSeed)&7),offset);radius=.5-dot(second,second);if(radius>0)value+=radius*radius*radius*radius*dot(Gradient(Hash(cellX+sx,cellY+sy,SimplexSeed)&7),second);radius=.5-dot(third,third);if(radius>0)value+=radius*radius*radius*radius*dot(Gradient(Hash(cellX+1,cellY+1,SimplexSeed)&7),third);return 70*value;} float Density(float3 p){return clamp(p.z-(SimplexBaseHeight+SimplexNoise(p.xy*SimplexFrequency)*SimplexAmplitude),-SdfClampDistance,SdfClampDistance);} float3 FacePosition(uint sample,uint face){int3 c=sample<9?SampleCoordinates[sample]:sample==9?int3(0,0,0):sample==10?int3(2,0,0):sample==11?int3(0,2,0):int3(2,2,0);if(face==0)return float3(0,c.x,c.y);if(face==1)return float3(2,c.y,c.x);if(face==2)return float3(c.y,0,c.x);if(face==3)return float3(c.x,2,c.y);if(face==4)return float3(c.x,c.y,0);return float3(c.y,c.x,2);} float3 WorldSample(TransitionRequest request,uint sample){return request.FineOrigin.xyz+FacePosition(sample,request.Face)/2*(float)ChunkSize*(float)request.FineStep;} float3 Normal(TransitionRequest request,float3 p,uint sampleA,uint sampleB,float t){float e=(float)request.FineStep;float3 a=WorldSample(request,sampleA),b=WorldSample(request,sampleB);float3 pa=lerp(a,b,t);float3 g=float3(Density(pa+float3(e,0,0))-Density(pa-float3(e,0,0)),Density(pa+float3(0,e,0))-Density(pa-float3(0,e,0)),Density(pa+float3(0,0,e))-Density(pa-float3(0,0,e)));float d=dot(g,g);if(d<1e-12)return request.Face==0?float3(-1,0,0):request.Face==1?float3(1,0,0):request.Face==2?float3(0,-1,0):request.Face==3?float3(0,1,0):request.Face==4?float3(0,0,-1):float3(0,0,1);return g*rsqrt(d);}
	[numthreads(64,1,1)] void MainCs(uint3 id:SV_DispatchThreadID){if(id.x>=(uint)BatchSize)return;TransitionRequest request=Requests[id.x];AllocationDescriptor allocation=Allocations[id.x];if((allocation.Flags&2)==0)return;uint baseSample=id.x*(uint)SampleCount;uint code=0;[unroll]for(uint bit=0;bit<9;bit++)if(Samples[baseSample+CaseOrder[bit]]<0)code|=1u<<bit;uint cellClass=Lookup[code],cls=cellClass&0x7f,counts=Lookup[GeometryOffset+cls],vertexCount=counts>>4,indexCount=(counts&15)*3;[unroll]for(uint v=0;v<12;v++){if(v>=vertexCount)break;uint edge=Lookup[VertexOffset+code*12+v],a=(edge>>4)&15,b=edge&15;float da=Samples[baseSample+a],db=Samples[baseSample+b],den=da-db,t=abs(den)>.000001?da/den:.5;t=clamp(t,0,1);float3 world=lerp(WorldSample(request,a),WorldSample(request,b),t);float3 p=(world-request.FineOrigin.xyz)*VoxelSize;float3 n=Normal(request,world,a,b,t);float3 tangent=abs(n.z)<.999?normalize(cross(float3(0,0,1),n)):float3(1,0,0);VoxelGpuVertex output;output.Position=p+allocation.DrawOrigin.xyz;output.Normal=n;output.Tangent=tangent;output.TexCoord=p.xy/128;OutputVertices[allocation.VertexOffset+v]=output;}uint triBase=TriangleOffset+cls*36;bool flip=(cellClass&0x80)!=0;[unroll]for(uint i=0;i<36;i+=3){if(i>=indexCount)break;uint a=Lookup[triBase+i],b=Lookup[triBase+i+1],c=Lookup[triBase+i+2];if(!flip){uint tmp=a;a=c;c=tmp;}uint target=allocation.IndexOffset+i;OutputIndices[target]=a;OutputIndices[target+1]=b;OutputIndices[target+2]=c;}}
}
