param(
	[string]$OutputPath = (Join-Path $PSScriptRoot '..\Code\Voxels\VoxelTransvoxelTransitionTables.cs')
)

$ErrorActionPreference = 'Stop'
$sourceUrl = 'https://raw.githubusercontent.com/EricLengyel/Transvoxel/51a494f03c5b024cd153b596bcc7152eb3cc93a6/Transvoxel.cpp'
$source = (Invoke-WebRequest -UseBasicParsing $sourceUrl).Content

function Get-TableBody([string]$Text, [string]$Pattern) {
	$match = [regex]::Match($Text, $Pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
	if (!$match.Success) { throw "Could not find table: $Pattern" }
	return $match.Groups['body'].Value
}

function Get-TopLevelBlocks([string]$Body) {
	$blocks = [System.Collections.Generic.List[string]]::new()
	$depth = 0
	$start = -1
	for ($index = 0; $index -lt $Body.Length; $index++) {
		switch ($Body[$index]) {
			'{' {
				if ($depth -eq 0) { $start = $index }
				$depth++
			}
			'}' {
				$depth--
				if ($depth -eq 0) { $blocks.Add($Body.Substring($start, $index - $start + 1)) }
				if ($depth -lt 0) { throw 'Unbalanced table braces.' }
			}
		}
	}
	if ($depth -ne 0) { throw 'Unbalanced table braces.' }
	return $blocks.ToArray()
}

function Get-NumericTokens([string]$Text) {
	$clean = [regex]::Replace($Text, '//[^\r\n]*', '')
	$matches = [regex]::Matches($clean, '0x[0-9A-Fa-f]+|\b\d+\b')
	$values = [System.Collections.Generic.List[int]]::new()
	foreach ($match in $matches) {
		$token = $match.Value
		if ($token.StartsWith('0x', [System.StringComparison]::OrdinalIgnoreCase)) {
			$values.Add( [Convert]::ToInt32( $token.Substring(2), 16 ) )
		} else {
			$values.Add( [Convert]::ToInt32( $token, 10 ) )
		}
	}
	return $values.ToArray()
}

function Convert-BytesToBase64([int[]]$Values) {
	$bytes = [byte[]]$Values
	return [Convert]::ToBase64String($bytes)
}

function Convert-UShortsToBase64([int[]]$Values) {
	$bytes = [byte[]]::new($Values.Length * 2)
	for ($index = 0; $index -lt $Values.Length; $index++) {
		$value = [uint16]$Values[$index]
		$bytes[$index * 2] = [byte]($value -band 0xff)
		$bytes[$index * 2 + 1] = [byte](($value -shr 8) -band 0xff)
	}
	return [Convert]::ToBase64String($bytes)
}

$classValues = Get-NumericTokens (Get-TableBody $source 'transitionCellClass\[512\][^=]*=\s*\{(?<body>.*?)\};')
if ($classValues.Count -ne 512) { throw "Expected 512 transition classes, got $($classValues.Count)." }

$cellRows = Get-TopLevelBlocks (Get-TableBody $source 'transitionCellData\[56\][^=]*=\s*\{(?<body>.*?)\};')
if ($cellRows.Count -ne 56) { throw "Expected 56 transition cell rows, got $($cellRows.Count)." }
$geometryCounts = [int[]]::new(56)
$triangleIndices = [int[]]::new(56 * 36)
for ($rowIndex = 0; $rowIndex -lt $cellRows.Count; $rowIndex++) {
	$values = Get-NumericTokens $cellRows[$rowIndex]
	$geometryCounts[$rowIndex] = $values[0]
	$triangleCount = $values[0] -band 0x0f
	$expectedValues = 1 + $triangleCount * 3
	if ($values.Count -ne $expectedValues) { throw "Transition cell row $rowIndex has $($values.Count - 1) indices; expected $($expectedValues - 1)." }
	for ($index = 0; $index -lt ($triangleCount * 3); $index++) { $triangleIndices[$rowIndex * 36 + $index] = $values[$index + 1] }
}

$cornerValues = Get-NumericTokens (Get-TableBody $source 'transitionCornerData\[13\][^=]*=\s*\{(?<body>.*?)\};')
if ($cornerValues.Count -ne 13) { throw "Expected 13 transition corners, got $($cornerValues.Count)." }

$vertexRows = Get-TopLevelBlocks (Get-TableBody $source 'transitionVertexData\[512\]\[12\][^=]*=\s*\{(?<body>.*?)\};')
if ($vertexRows.Count -ne 512) { throw "Expected 512 transition vertex rows, got $($vertexRows.Count)." }
$vertexValues = [int[]]::new(512 * 12)
for ($rowIndex = 0; $rowIndex -lt $vertexRows.Count; $rowIndex++) {
	$values = Get-NumericTokens $vertexRows[$rowIndex]
	$vertexCount = ($geometryCounts[$classValues[$rowIndex] -band 0x7f] -shr 4)
	if ($values.Count -ne $vertexCount) { throw "Transition vertex row $rowIndex has $($values.Count) entries; expected $vertexCount." }
	for ($index = 0; $index -lt $values.Count; $index++) { $vertexValues[$rowIndex * 12 + $index] = $values[$index] }
}

$hash = [System.Security.Cryptography.SHA256]::Create()
$sourceHash = ([BitConverter]::ToString($hash.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($source)))).Replace('-', '').ToLowerInvariant()
$classBase64 = Convert-BytesToBase64 $classValues
$geometryBase64 = Convert-BytesToBase64 $geometryCounts
$indicesBase64 = Convert-BytesToBase64 $triangleIndices
$cornerBase64 = Convert-BytesToBase64 $cornerValues
$vertexBase64 = Convert-UShortsToBase64 $vertexValues

$content = @"
// Generated by scripts/import-transvoxel-transition-tables.ps1.
// Official source revision: 51a494f03c5b024cd153b596bcc7152eb3cc93a6
// Official source SHA-256 (UTF-8): $sourceHash
// https://github.com/EricLengyel/Transvoxel
// Licensed under the MIT License; see Archive/ThirdParty/Transvoxel-LICENSE.txt.
internal static class VoxelTransvoxelTransitionTables
{
	private const string CellClassBase64 = "$classBase64";
	private const string GeometryCountsBase64 = "$geometryBase64";
	private const string TriangleIndicesBase64 = "$indicesBase64";
	private const string CornerDataBase64 = "$cornerBase64";
	private const string VertexDataBase64 = "$vertexBase64";

	public static readonly byte[] CellClass = System.Convert.FromBase64String( CellClassBase64 );
	public static readonly byte[] GeometryCounts = System.Convert.FromBase64String( GeometryCountsBase64 );
	public static readonly byte[] TriangleIndices = System.Convert.FromBase64String( TriangleIndicesBase64 );
	public static readonly byte[] CornerData = System.Convert.FromBase64String( CornerDataBase64 );
	public static readonly ushort[] VertexData = DecodeUShorts( VertexDataBase64 );

	private static ushort[] DecodeUShorts( string base64 )
	{
		var bytes = System.Convert.FromBase64String( base64 );
		var values = new ushort[bytes.Length / sizeof( ushort )];
		System.Buffer.BlockCopy( bytes, 0, values, 0, bytes.Length );
		return values;
	}
}
"@

$fullOutputPath = if ([System.IO.Path]::IsPathRooted($OutputPath)) {
	[System.IO.Path]::GetFullPath($OutputPath)
} else {
	[System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot $OutputPath))
}
$parent = [System.IO.Path]::GetDirectoryName($fullOutputPath)
[System.IO.Directory]::CreateDirectory($parent) | Out-Null
[System.IO.File]::WriteAllText($fullOutputPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Output "Imported $($classValues.Count) cases, $($cellRows.Count) classes, $($vertexValues.Count) vertex entries to $fullOutputPath"
